# Generated by Django 6.1.1 on 2026-09-25 11:56

import CirclesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CirclesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='name',
            new_name='circle_name',
        ),
        migrations.AddField(
            model_name='circle',
            name='circle_tag',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circle',
            name='invite_code',
            field=models.CharField(default=CirclesApp.models.create_code, max_length=12, unique=True),
        ),
    ]
