# Generated by Django 6.1.1 on 2026-09-26 12:31

import CirclesApp.models
import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CirclesApp', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2026, 9, 26)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2026, 9, 26)),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=CirclesApp.models.get_end_of_day),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
