# Generated by Django 6.1.1 on 2026-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CirclesApp', '0005_remove_event_end_date_remove_event_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='days_repeated',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='event',
            name='weeks_count',
            field=models.IntegerField(default=1),
        ),
    ]
