# Generated by Django 6.1.1 on 2026-09-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CirclesApp', '0006_event_days_repeated_event_weeks_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='days_repeated',
        ),
        migrations.RemoveField(
            model_name='event',
            name='weeks_count',
        ),
    ]
