# Generated by Django 6.1.1 on 2026-10-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CirclesApp', '0010_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
