# Generated by Django 6.1.1 on 2026-10-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CirclesApp', '0011_userprofile_free_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poll_type',
            field=models.CharField(choices=[('majority_all', 'Majority (All Members)'), ('majority_voters', 'Majority (Voters Only)'), ('optin', 'Opt-in (Voters Only)')], default='majority_voters', help_text='Majority types need over 50% Yes. Opt-in has no threshold: it resolves once everyone has voted or the organizer finalizes it.', max_length=20),
        ),
    ]
